# Site
name: 'Pufflepost'
title: "Pufflepost"
description: "A modern blog!" # used by search engines
logo: 'assets/images/Pufflepost Logo Wide.svg'
favicon: 'assets/images/favicon.ico'
baseurl: ""
google_analytics: G-JD1B356GRY
url: "https://pufflepost.com"
disqus: 'pufflepost'
email: 'pufflepost@gmail.com'
include: ["_pages"]
permalink: /:title/


# Authors
authors:
  Aman:
    name: Aman
    display_name: Aman Garg
    avatar: assets/images/avatar.webp
    email: amangarg599@gmail.com
    web: https://www.instagram.com/amangarg._/
    twitter: https://twitter.com/pufflepost/
    linkedin: https://linkedin.com/in/amangarg0599
    facebook: http://www.facebook.com/pufflepost/
    Leetcode: https://www.leetcode.com/amangarg0599
    description: "Author of this Blog, Definitely not a cyborg."
 


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
# highlighter: rogue
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : false



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-1722804840732560"
adsense-data-ad-slot: "7438894989"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
